- name: Cisco example
  hosts: routers
  gather_facts: false

  tasks:
    - name: Execute show ip interface brief before the change
      ios_command:
        commands: show ip interf brief
      register: output

    - name: print output
      debug:
        var: output.stdout_lines

    - name: Create a loopback interface
      cisco.ios.ios_interfaces:
        config:
        - name: Loopback 100
          description: Added and Merged by Ansible
          enabled: true

    - name: Execute show ip interface brief after the change
      ios_command:
        commands: show ip interf brief
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
                                           